'use strict';
const inquiryDraftMemory=new Map();
const InquiryDraft = {
 key(vault,id,phase){return ['ala.inquiry',vault,id,phase].join(':');},
 read(storage,key){try{return inquiryDraftMemory.get(key)||JSON.parse(storage.getItem(key)||'{}');}catch{return inquiryDraftMemory.get(key)||{}; }},
 write(storage,key,value){inquiryDraftMemory.set(key,value);try{storage.setItem(key,JSON.stringify(value));return true;}catch{return false;}},
 remove(storage,key){inquiryDraftMemory.delete(key);try{storage.removeItem(key);}catch{}},
 request(saved,body,id){const signature=JSON.stringify(body);return saved.signature===signature?saved:{signature,body:{...body,request_id:id()}};}
};
if(typeof module!=='undefined'&&module.exports)module.exports=InquiryDraft;
if(typeof words!=='undefined'){
Object.assign(words.fi,{inquiry:'Ohjattu tutkimuskysymys',inquiryIntro:'Kehitä aineistoon liittyvää omaa kysymystäsi vaihe kerrallaan. Ohjauskysymykset ovat valmiita harjoittelurakenteita, eivät mallin arvioita.',inquiryNew:'Aloita valitusta aineistokohdasta',inquiryContinue:'Jatka harjoitusta',inquiryHistory:'Tallennetut harjoitukset',inquiryEmpty:'Ei vielä ohjattuja harjoituksia.',inquiry_attempt:'Oma yritys',inquiry_clarify:'Täsmennä',inquiry_revise:'Korjaa',inquiry_transfer:'Sovella itsenäisesti',inquiry_reflect:'Reflektoi',inquiry_complete:'Valmis',inquiryNext:'Tallenna ja jatka',inquiryHint:'Pyydä seuraava vihje',inquiryPractice:'Palaa tuettuun harjoitteluun',inquiryOriginal:'Alkuperäinen yrityksesi',inquirySource:'Harjoituksen lähde',inquirySaved:'Vaihe tallennettu',inquirySupport:'Käytetyt vihjeet',inquiryIndependent:'Soveltamisvaiheessa tämän harjoituksen aineisto ja vihjeet on piilotettu. Muut sovellukset ja materiaalit eivät ole estettyjä. Kyseessä on itsenäinen harjoitus, ei valvottu koe.',inquiryDone:'Oma yritys, korjaus, soveltaminen ja reflektio ovat tallessa. Tämä ei anna arvosanaa tai todista osaamista.',inquiryReload:'Lataa tallennettu tilanne',inquirySaveError:'Tallennus ei varmistunut. Luonnos säilyy tässä selaimessa. Voit yrittää samaa tallennusta uudelleen tai ladata tallennetun tilanteen.',inquiry_revision_conflict:'Harjoitus muuttui toisessa ikkunassa. Lataa tallennettu tilanne; oma luonnos säilyy.',inquiry_request_conflict:'Saman pyynnön sisältö muuttui. Lataa tallennettu tilanne.',inquiry_answer_required:'Kirjoita vastaus (enintään 20 000 merkkiä).',inquiry_help_unavailable:'Vihjeet ovat käytössä täsmennys- ja korjausvaiheessa oman yrityksen jälkeen.',inquiry_hints_used:'Kaikki tämän vaiheen vihjeet on jo avattu.',inquiry_not_found:'Harjoitusta ei löydy tästä oppimisvarastosta.',invalid_inquiry_request:'Harjoituspyyntö ei ole kelvollinen.',inquiry_limit:'Harjoituksen vaiheiden enimmäismäärä täyttyi.',inquiryStored:'Palvelimelle tallennettu',inquiryDraftLocal:'Luonnos tallentuu tähän selaimeen.',inquiryDraftFailed:'Selaimen luonnostallennus ei onnistunut. Tallenna vaihe ennen sulkemista.'});
Object.assign(words.en,{inquiry:'Guided research question',inquiryIntro:'Develop your own source-related question one step at a time. The prompts are fixed learning scaffolds, not model assessments.',inquiryNew:'Start from the selected source',inquiryContinue:'Continue practice',inquiryHistory:'Saved practice',inquiryEmpty:'No guided practice yet.',inquiry_attempt:'Your first attempt',inquiry_clarify:'Clarify',inquiry_revise:'Revise',inquiry_transfer:'Apply independently',inquiry_reflect:'Reflect',inquiry_complete:'Complete',inquiryNext:'Save and continue',inquiryHint:'Request the next hint',inquiryPractice:'Return to supported practice',inquiryOriginal:'Your original attempt',inquirySource:'Practice source',inquirySaved:'Step saved',inquirySupport:'Hints used',inquiryIndependent:'This practice hides its source and hints during application. Other apps and materials are not blocked. This is independent practice, not a supervised exam.',inquiryDone:'Your original attempt, revision, application and reflection are saved. This does not award a grade or certify competence.',inquiryReload:'Load saved state',inquirySaveError:'Save was not confirmed. The draft remains in this browser. Retry the same save or load the saved state.',inquiry_revision_conflict:'This practice changed in another window. Load the saved state; your draft is retained.',inquiry_request_conflict:'The content of this request changed. Load the saved state.',inquiry_answer_required:'Write an answer (up to 20,000 characters).',inquiry_help_unavailable:'Hints are available in clarification and revision after your own attempt.',inquiry_hints_used:'All hints for this step have been opened.',inquiry_not_found:'This practice was not found in this vault.',invalid_inquiry_request:'Invalid practice request.',inquiry_limit:'The practice step limit was reached.',inquiryStored:'Saved on the server',inquiryDraftLocal:'Your draft is saved in this browser.',inquiryDraftFailed:'The browser could not save this draft. Save the step before closing.'});
}
let inquirySerial=0;
const inquiryPhases=['attempt','clarify','revise','transfer','reflect','complete'];
function inquiryPrompt(phase,title){const fi=S.settings.language==='fi';const text=fi?{
 attempt:`Millaisen tutkittavan kysymyksen muodostaisit aiheesta ”${title}”?`,
 clarify:'Mitä havaittavaa näyttöä tarvitsisit vastataksesi omaan kysymykseesi?',
 revise:'Miten muotoilisit kysymyksesi uudelleen niin, että sen rajaus ja tutkittavuus ovat selkeämmät?',
 transfer:'Miten soveltaisit kysymystäsi itse valitsemaasi uuteen tilanteeseen?',
 reflect:'Mikä muuttui alkuperäisestä ajatuksestasi ja miksi muutos auttaa tutkimista?'
 }:{attempt:`What researchable question would you formulate about “${title}”?`,clarify:'What observable evidence would you need to answer your question?',revise:'How would you revise your question to make its scope and researchability clearer?',transfer:'How would you apply your question to a new situation of your choice?',reflect:'What changed from your original idea, and why does that change help the inquiry?'};return text[phase]||t('inquiryDone');}
function inquiryHintText(level){const fi=S.settings.language==='fi';return (fi?['Valitse yksi käsite ja rajaa tilanne, jossa sitä tarkastelet.','Pohdi, mitä voisit havaita tai verrata. Erota havainto omasta oletuksestasi.','Palaa alla olevaan lähdekatkelmaan. Valitse siitä käsite ja kuvaa, millainen näyttö voisi tukea siihen liittyvää väitettä.']:['Choose one concept and a specific situation to examine.','Consider what you could observe or compare. Separate an observation from an assumption.','Revisit the source excerpt below. Choose one concept and describe evidence that could support a related claim.'])[level-1];}
function mountInquiry(){if(S.view==='lecture')return;const host=$('.wide');if(!host||$('#inquiryOpen'))return;const button=document.createElement('button');button.id='inquiryOpen';button.className='primary inquiry-open';button.textContent=t('inquiry');button.onclick=inquiryHub;host.prepend(button);}
async function inquiryHub(){const serial=++inquirySerial,vault=S.active;try{const rows=await api('/api/inquiry',undefined,{headers:{'X-ALA-Vault':vault}});if(serial!==inquirySerial||vault!==S.active)return;modal(t('inquiry'),`<p>${t('inquiryIntro')}</p><div class="context-tag">${h(contextLabel())}</div><button class="primary" id="inquiryStart" ${S.doc?'':'disabled'}>${t('inquiryNew')}</button><h3>${t('inquiryHistory')}</h3>${rows.length?rows.map(a=>`<article class="list-card"><strong>${h(a.source.title)}</strong><p>${t('inquiry_'+a.state.phase)} · ${new Date(a.updated).toLocaleString(S.settings.language)}</p><button data-inquiry="${a.id}">${t('inquiryContinue')}</button></article>`).join(''):`<p>${t('inquiryEmpty')}</p>`}`,()=>{const did=S.doc?.id,page=S.page;$('#inquiryStart').onclick=async()=>{const button=$('#inquiryStart');button.disabled=true;const key=InquiryDraft.key(vault,'start',did+':'+page);try{const saved=InquiryDraft.read(localStorage,key);const req=InquiryDraft.request(saved,{document_id:did,page},()=>crypto.randomUUID());InquiryDraft.write(localStorage,key,req);const result=await api('/api/inquiry/start',req.body,{headers:{'X-ALA-Vault':vault}});InquiryDraft.remove(localStorage,key);if(serial===inquirySerial&&vault===S.active)showInquiry(result,vault);}catch(e){fail(e)}finally{button.disabled=false}};document.querySelectorAll('[data-inquiry]').forEach(b=>b.onclick=()=>openInquiry(b.dataset.inquiry,vault));$('#closeModal').onclick=()=>{inquirySerial++;closeModal()}})}catch(e){if(serial===inquirySerial)fail(e)}}
async function openInquiry(id,vault){const serial=++inquirySerial;try{const value=await api('/api/inquiry/'+id,undefined,{headers:{'X-ALA-Vault':vault}});if(serial===inquirySerial&&vault===S.active)showInquiry(value,vault)}catch(e){if(serial===inquirySerial)fail(e)}}
function showInquiry(attempt,vault){const serial=++inquirySerial,state=attempt.state,phase=state.phase,key=InquiryDraft.key(vault,attempt.id,phase),saved=InquiryDraft.read(localStorage,key);const levels=state.hints.filter(x=>x.phase===phase);const independent=phase==='transfer';const done=phase==='complete';modal(t('inquiry'),`<div class="inquiry-steps" aria-label="${t('inquiry')}">${inquiryPhases.map((p,i)=>`<span class="${p===phase?'current':''}">${i+1}. ${t('inquiry_'+p)}</span>`).join('')}</div><p class="meta">${h(attempt.source.name)} · ${attempt.page}</p><p class="notice">${t(independent?'inquiryIndependent':done?'inquiryDone':'inquiryIntro')}</p><h3>${h(inquiryPrompt(phase,attempt.source.title))}</h3>${!independent?`<details><summary>${t('inquirySource')}</summary><p class="quote">${h(attempt.source.text)}</p></details>`:''}${state.original&&!independent?`<details><summary>${t('inquiryOriginal')}</summary><p class="quote">${h(state.original)}</p></details>`:''}${levels.map(x=>`<aside class="notice">${x.level}. ${h(inquiryHintText(x.level))}${x.level===3?`<p class="quote">${h(attempt.source.text.slice(0,650))}</p>`:''}</aside>`).join('')}${done?['original','clarification','revised','transfer','reflection'].map((field,i)=>`<article class="list-card"><h3>${t('inquiry_'+inquiryPhases[i])}</h3><p class="inquiry-answer">${h(state[field])}</p></article>`).join(''):`<form id="inquiryForm" class="stack"><label>${t('answer')}<textarea id="inquiryAnswer" maxlength="20000" required></textarea></label><small id="inquiryDraftStatus">${t('inquiryDraftLocal')}</small><button class="primary" id="inquirySubmit">${t('inquiryNext')}</button></form>`}<div class="buttons">${['clarify','revise'].includes(phase)?`<button id="inquiryHint" ${levels.length>=3?'disabled':''}>${t('inquiryHint')} (${levels.length}/3)</button>`:''}${independent?`<button id="inquiryPractice">${t('inquiryPractice')}</button>`:''}<button id="inquiryReload">${t('inquiryReload')}</button></div><p>${t('inquirySupport')}: ${state.hints.length}</p><p id="inquiryError" role="status" class="note-error"></p>`,()=>{
 const input=$('#inquiryAnswer');if(input)input.value=saved.text||'';
 const persist=()=>{if(!input)return;try{const latest=InquiryDraft.read(localStorage,key);if(!InquiryDraft.write(localStorage,key,{...latest,text:input.value}))throw Error('storage');}catch{if($('#inquiryDraftStatus'))$('#inquiryDraftStatus').textContent=t('inquiryDraftFailed')}};
 if(input)input.oninput=persist;
 $('#closeModal').onclick=()=>{persist();inquirySerial++;closeModal()};
 $('#inquiryReload').onclick=()=>{persist();openInquiry(attempt.id,vault)};
 async function turn(action){persist();const buttons=[...$('#modal-root').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const body={attempt_id:attempt.id,expected_revision:attempt.revision,action};if(action==='answer')body.text=input.value;const current=InquiryDraft.read(localStorage,key);const request=InquiryDraft.request(current.pending||{},body,()=>crypto.randomUUID());InquiryDraft.write(localStorage,key,{...current,pending:request});await api('/api/tutor/turn',request.body,{headers:{'X-ALA-Vault':vault}});if(action==='answer')InquiryDraft.remove(localStorage,key);else InquiryDraft.write(localStorage,key,{text:input?.value||''});if(serial===inquirySerial&&vault===S.active){await openInquiry(attempt.id,vault);toast(t('inquirySaved'));}}catch(e){if(serial===inquirySerial&&$('#inquiryError'))$('#inquiryError').textContent=['inquiry_revision_conflict','inquiry_request_conflict'].includes(e.message)?t(e.message):t('inquirySaveError');}finally{buttons.forEach(b=>b.disabled=false)}}
 $('#inquiryForm')?.addEventListener('submit',e=>{e.preventDefault();turn('answer')});$('#inquiryHint')?.addEventListener('click',()=>turn('hint'));$('#inquiryPractice')?.addEventListener('click',()=>turn('practice'));
 },true);}

